name: PR (develop)

on:
  pull_request:
    branches: ['develop']

jobs:
  run-lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          npm run lint:check 2>&1 | \
          # generate full-lint.log
          tee "full-lint.log"
          # save exit code
          exit_code="${PIPESTATUS[0]}"
          # parsing and generate summary-lint-errors.log
          grep -E '^\[warn\]|^Error:|^Warning:' "full-lint.log" > "summary-lint-errors.log" || \
          echo "No lint errors found." > "summary-lint-errors.log"
          # execute exit code
          exit "$exit_code"

      - name: Upload full-lint.log
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: lint-results
          path: |
            # full-lint.log
            full-lint.log
            # summary-lint-errors.log
            summary-lint-errors.log
