name: CI

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  run-lint:
    name: Run ESLint
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: ['22']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          set -o pipefail
          npm run lint 2>&1 | \
          tee full-lint.log
          
          exit_code="${PIPESTATUS[0]}"

          if grep -E '^\[warn\]|^Error:|^Warning:' full-lint-${{ matrix.node-version }}.log > summary-lint-errors-${{ matrix.node-version }}.log; then
            echo "ESLint issues found."
          else
            echo "No ESLint errors." > summary-lint-errors-${{ matrix.node-version }}.log
          fi
          
          if [ $exit_code -ne 0 ]; then
            echo ""
            echo "❌ ESLint errors found. See summary-lint-errors-${{ matrix.node-version }}.log for details."
            echo ""
          else
            echo ""
            echo "✅ No lint errors."
            echo ""
          fi
          
          exit "$exit_code"

      - name: Upload lint logs
        uses: actions/upload-artifact@v4
        with:
          name: lint-results-${{ matrix.node-version }}
          path: |
            full-lint-${{ matrix.node-version }}.log
            summary-lint-errors-${{ matrix.node-version }}.log

  run-tests:
    name: Run Tests
    runs-on: 'ubuntu-latest'
    needs: [ 'run-lint' ]

    strategy:
      matrix:
        node-version: ['22']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests and generate logs
        run: |
          set -o pipefail
      
          echo ""
          echo "🚀 Run Tests..."
      
          npm run test -- --ci 2>&1 | \
          tee "full-tests-${{ matrix.node-version }}.log"
      
          exit_code="${PIPESTATUS[0]}"
      
          grep -E "Test Suites:|Tests:|Snapshots:|Time:" "full-tests-${{ matrix.node-version }}.log" > \
          summary-tests-${{ matrix.node-version }}.log || echo "❌ Tests not found." > summary-tests-${{ matrix.node-version }}.log
      
          awk '/Summary of all failing tests/,/Test Suites/{if ($0 !~ /Test Suites/) print}' \
          "full-tests-${{ matrix.node-version }}.log" > \
          summary-tests-errors-${{ matrix.node-version }}.log || echo "✅ All tests passed successfully." > summary-tests-errors-${{ matrix.node-version }}.log
      
          if [ $exit_code -ne 0 ]; then
            echo ""
            echo "❌ Tests are failed. Please check summary-tests-errors-${{ matrix.node-version }}.log."
            echo ""
          else
            echo ""
            echo "✅ All tests are passed successfully."
            echo ""
          fi
          
          exit "$exit_code"

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: tests-results-${{ matrix.node-version }}
          path: |
            full-tests-results-${{ matrix.node-version }}.log
            summary-tests-results-${{ matrix.node-version }}.log
            summary-tests-errors-${{ matrix.node-version }}.log
            

  generate-report:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: ['run-lint', 'run-tests']
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Generate Test Report
        run: |
          CI_MARKER="# ✅ CI Report - $(TZ="Europe/Kyiv" date +"%H:%M %d/%m/%Y")"
          {
            echo "$CI_MARKER"
            echo ""
          } > report.txt

          # 📝 Lint Report
          {
            echo "## 📝 Lint Report"
            echo ""

            SUMMARY_FILE="all-artifacts/lint-results/summary-lint-errors.log"

            if [[ -f "$SUMMARY_FILE" ]]; then
              if grep -q -E '^\[warn\]|^Error:' "$SUMMARY_FILE"; then
                echo "**❌ Lint Errors Found:**"
                echo '```'
                cat "$SUMMARY_FILE"
                echo '```'
              else
                echo '```'
                echo "✅ No lint issues found."
                echo '```'
              fi
            else
              echo "⚠️ Lint report not found."
            fi

            printf "\n"
          } >> report.txt

          # 🧪 Test Reports
          TEST_REPORTS_FOUND=false
          {
            echo "## 🧪 Test Results"
            echo ""

            for folder in $(find all-artifacts -type d -name "tests-results-*"); do
              TEST_REPORTS_FOUND=true
              TEST_VERSION=$(basename "$folder")
              NODE_VERSION=$(echo "$TEST_VERSION" | cut -d'-' -f3)

              SUMMARY_FILE="$folder/summary-tests-results-${NODE_VERSION}-${MONGO_VERSION}.log"
              ERRORS_FILE="$folder/summary-tests-errors-${NODE_VERSION}-${MONGO_VERSION}.log"

              echo "**🔹 Node.js Version:** $NODE_VERSION"
              echo ""

              if [[ -f "$SUMMARY_FILE" ]]; then
                echo "**Test Summary:**"
                echo '```'
                cat "$SUMMARY_FILE"
                echo '```'
              else
                echo "⚠️ No test summary available."
              fi

              if [[ -s "$ERRORS_FILE" ]]; then
                echo "**❌ Test Errors:**"
                echo '```'
                cat "$ERRORS_FILE"
                echo '```'
              fi

              echo ""
            done

            if [[ "$TEST_REPORTS_FOUND" == false ]]; then
              echo "⚠️ No test results available."
            fi

            echo ""
          } >> report.txt


      - name: Publish Report in GitHub Actions Summary
        run: cat report.txt >> "$GITHUB_STEP_SUMMARY"

      - name: Update CI Report in PR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [[ -z "$PR_NUMBER" ]]; then
            echo "No PR associated, skipping update."
            exit 0
          fi

          COMMENT_ID=$(gh api "repos/:owner/:repo/issues/$PR_NUMBER/comments" --jq '.[] | select(.user.login=="github-actions[bot]") | select(.body | contains("# ✅ CI Report")) | .id')

          if [[ -n "$COMMENT_ID" ]]; then
            echo "Updating existing CI report comment: $COMMENT_ID"
            gh api "repos/:owner/:repo/issues/comments/$COMMENT_ID" -X PATCH -f body="$(cat report.txt)"
          else
            echo "No previous CI report found, creating a new one..."
            gh pr comment "$PR_NUMBER" --body-file "report.txt"
          fi

